#!/usr/bin/env python3
import click
from pymap3d import enu
import os
import sys
import math
import copy
import numpy as np
import numpy.typing as npt

# local
from romea_path_tools.path import Path


def create_points(path: Path, new_path: Path, offset: list, angle: float):
    cos_angle = math.cos(angle)
    sin_angle = math.sin(angle)

    new_path.columns = path.columns

    xi = path.columns.index("x")
    yi = path.columns.index("y")

    for point in path.points:
        new_point = copy.copy(point)
        new_point[xi] = offset[0] + point[xi] * cos_angle - point[yi] * sin_angle
        new_point[yi] = offset[1] + point[xi] * sin_angle + point[yi] * cos_angle
        new_path.points.append(new_point)

    new_path.create_sections(path.section_indexes())
    new_path.row_zones = [(z[0], z[1]) for z in path.row_zones]


def initial_path_direction(path: Path) -> npt.NDArray:
    points = path.points
    if len(points) < 2:
        raise RuntimeError("Not enough points to compute an initial direction vector")
    diff = np.array(points[1][:2]) - np.array(points[0][:2])
    return diff / np.linalg.norm(diff)


def rotate_from_dir(direction: npt.NDArray, vector: npt.NDArray) -> npt.NDArray:
    perpendicular = np.array([-direction[1], direction[0]])
    rotated_vector = (vector[0] * direction) + (vector[1] * perpendicular)
    return rotated_vector


@click.command()
@click.argument("path_in", type=click.Path(exists=True))
@click.argument("path_out", type=click.Path())
@click.option(
    "-a",
    "--anchor",
    type=float,
    nargs=3,
    default=None,
    metavar="LAT LON ALT",
    help="a new anchor (format: latitude longitude altitude)",
)
@click.option(
    "-o",
    "--offset",
    type=float,
    nargs=2,
    default=None,
    metavar="X Y",
    help="an (x, y) offset from the orientation of the first point (format: x y)",
)
@click.option(
    "-r",
    "--rotation",
    type=float,
    default=None,
    metavar="ANGLE",
    help="apply a rotation to the points (in degrees)",
)
@click.option(
    "-t",
    "--type",
    "fmt",
    default=None,
    metavar="TYPE",
    type=click.Choice(["romea_v1", "tiara_v2", "tiara_v4", "csv", "kml", "wgs84_csv", "geojson"]),
    help="file format of the generated path. If not specified, the file extension is used.",
)
@click.option("-f", "--force", is_flag=True, help="override existing output file")
@click.option(
    "--infer-rows",
    is_flag=True,
    help="when converting to tiara_v4, try to infer row boundaries from work zone annotations",
)
def main(path_in, path_out, anchor, offset, rotation, fmt, force, infer_rows):
    """Convert a path file to a new one with some transformations.

    Known extensions: .txt (romea), .traj (tiara), .csv, .wgs84.csv, .kml, .geojson.
    """
    if not force and os.path.exists(path_out):
        print(f"[error] Failed to create file '{path_out}': file already exists", file=sys.stderr)
        if input("Do you want to override it? [y/N] ") not in ["y", "Y", "o", "O"]:
            exit(1)

    path = Path.load(path_in)
    new_path = Path()

    off = [0.0, 0.0]

    if rotation:
        angle = rotation * math.pi / 180.0
    else:
        angle = 0.0

    if offset:
        off = list(offset)
        dir = initial_path_direction(path)
        off = rotate_from_dir(dir, off)

    if anchor:
        new_path.anchor = list(anchor)
        path_anchor = path.anchor
        new_anchor = new_path.anchor

        print(f"current anchor: {path_anchor}")
        print(f"new anchor: {new_anchor}")

        e, n, u = enu.geodetic2enu(
            path_anchor[0],
            path_anchor[1],
            path_anchor[2],
            new_anchor[0],
            new_anchor[1],
            new_anchor[2],
        )
        off[0] += e
        off[1] += n
        print(f"offset: {off}")

    else:
        new_path.anchor = path.anchor

    create_points(path, new_path, off, angle)
    new_path.annotations = copy.copy(path.annotations)

    if fmt:
        if fmt == "csv":
            new_path.save_csv(path_out)
        elif fmt == "kml":
            new_path.save_kml(path_out)
        elif fmt == "wgs84_csv":
            new_path.save_wgs84_csv(path_out)
        elif fmt == "geojson":
            new_path.save_geojson(path_out)
        elif fmt == "romea_v1":
            print("[error] output format 'romea_v1' is not supported", file=sys.stderr)
        elif fmt == "tiara_v4":
            if not new_path.row_zones and infer_rows:
                new_path.infer_row_zones_from_annotations()
            new_path.save_v4(path_out, include_turn_geometry=True)
        else:
            new_path.save(path_out)
    else:
        if path_out.endswith("wgs84.csv"):
            new_path.save_wgs84_csv(path_out)
        elif path_out.endswith(".csv"):
            new_path.save_csv(path_out)
        elif path_out.endswith(".kml"):
            new_path.save_kml(path_out)
        elif path_out.endswith(".geojson"):
            new_path.save_geojson(path_out)
        elif path_out.endswith(".txt"):
            print("[error] output format 'romea_v1' is not supported", file=sys.stderr)
        elif path_out.endswith(".traj"):
            new_path.save(path_out)
        else:
            print(f"[error] unknown file extension for '{path_out}'", file=sys.stderr)


if __name__ == "__main__":
    main()
