#!/usr/bin/env python3
import click
import matplotlib.pyplot as plt
from pymap3d import enu
import numpy as np

from romea_path_tools.path import Path
from romea_path_tools.plotter import plot_path


def get_anchor_offset(a, b):
    e, n, u = enu.geodetic2enu(*a, *b)
    return np.array([e, n])


@click.command()
@click.argument('path', type=click.Path(exists=True))
@click.argument('paths', type=click.Path(exists=True), nargs=-1)
def main(path, paths):
    """Plot several paths in the coordinate (anchor) of the first one.

    If the filename ends with '.json', it is considered as a tiara trajectory, else it is
    considered as a romea trajectory (old version).
    """
    fig, ax = plt.subplots()
    handles = {}

    print(f"Loading file '{path}'")
    first_path = Path.load(path)
    ref_anchor = first_path.anchor
    plot_path(first_path, handles)

    for path_name in paths:
        print(f"Loading file '{path_name}'")
        p = Path.load(path_name)
        offset = get_anchor_offset(p.anchor, ref_anchor)
        plot_path(p, handles, offset)

    fig.set_size_inches(12, 8)
    ax.axis('equal')
    ax.grid(True)
    ax.margins(0.02, 0.02)
    ax.tick_params(axis="y", direction="in", pad=-22)
    ax.tick_params(axis="x", direction="in", pad=-15)
    ax.legend(handles.values(), handles.keys())
    plt.subplots_adjust(left=0, bottom=0, right=1, top=1, wspace=0, hspace=0)

    plt.show()


if __name__ == '__main__':
    main()
